Improve efficiency in memory trace and device->host mem-copy
Green-Phys/green-gpu pull request #5
Opened 2024-10-11 20:09 UTC by gauravharsha

Proposing the following changes

1. Current copy of new self-energy from CUDA device to Host memory uses `cudaMemcpy`. This blocks the processes and further execution of kernels. Replacing this with `cudaMemcpyAsync`. This should, in principle, speed up the code.
2. To implement (1), function signatures are updated. Two-step process involving `cudaMemcpy` to a buffer on host memory, followed by writing the host buffer to shared-memory Self-energy is introduced.
3. Adding a function to measure total FLOPs achieved (including read/write steps).
4. Updates in error handling for Cholesky / LU failures when computing polarization P from P0.

2024-10-11 22:12 UTC, egull requested changes
OK. On Monday need to go over shared memory sync and effective locking/unlocking.

For now I propose to split this into the three issues: The FLOP count (harmless), the trap/abort (also harmless), and the shared mem.

The first two we can get done right away. The third needs work.

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +      MPI_Win_lock_all(MPI_MODE_NOCHECK, sigma_tau_host_shared.win());
This we need to discuss. It's fairly catastrophic in amulti-GPU environment: only ONE MPI process will enter the section below at a time... I believe there's no reason for that.

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +                copy_Sigma(sigma_tau_host_shared.object(), Sigmak_stij, k_reduced_id, _nts, _ns);
why can't the lock be around this?

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +                copy_Sigma_2c(sigma_tau_host_shared.object(), Sigmak_stij, k_reduced_id, _nts);
...and around this?

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +              qkpt->compute_second_tau_contraction(qpt.Pqk_tQP(qkpt->all_done_event(), qkpt->stream(), need_minus_q));
even here, you probably don't want to lock out everybody but do the lock/unlock jsut around the memcpy

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +      MPI_Win_unlock_all(sigma_tau_host_shared.win());
this is silly here? Why? we always have lock/unlock in pairs

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +      MPI_Win_sync(sigma_tau_host_shared.win());
why so far outside the write?

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +      MPI_Win_sync(sigma_tau_host_shared.win());
actually I'm totally confused about the need to sync at all.

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
> +    // wait for all qkpts to complete
propose to put the lock/unlock magic right around the memcpy and keep it very local there.

2024-10-11 22:12 UTC, egull commented on src/cu_routines.cu
>      }
ditto

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +        throw std::runtime_error("failure allocating Gk_tsij on host");
sure we can allocate another buffer on the host. That's totally fine, no reason to preserve memory here.

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +    // TODO: In my understanding, the lock is only required for RAXPY part now, so we should move them inside the first if condition
correct.

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +      cleanup_req_ = true;
yes, correct.

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +      std::memcpy(Sigma_stij_host, Sigmak_stij_buffer_, ns_ * ntnao2_ * sizeof(cxx_complex));
we were talking about combining buffers here. Possibly that was done already.

2024-10-11 22:12 UTC, egull commented on src/green/gpu/cugw_qpt.h
> +    bool cleanup_req_;
propose making a destructor that throws an exception if cleanup_req_ is true and a constructor that sets it to false.

2024-10-11 22:12 UTC, egull commented on src/gw_gpu_kernel.cpp
> +
YES! GREAT!

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +    if (cleanup_req_) {
I would put the shared window lock just here

2024-10-11 22:12 UTC, egull commented on src/cugw_qpt.cu
> +      cleanup_req_ = false;
I would put the shared window unlock just here.

2024-10-14 12:36 UTC, iskakoff requested changes

2024-10-14 12:36 UTC, iskakoff commented on src/cu_routines.cu
> +      MPI_Win_lock_all(MPI_MODE_NOCHECK, sigma_tau_host_shared.win());
@egull that's not how `MPI_Win_lock_all(MPI_MODE_NOCHECK, win)` works. This call only asserts the start of the communication epoch, and no synchronization is done here. To do the memory synchronization one has to call `MPI_Win_sync`, which is done bellow after the loop. 

However, there is much more dangerous things going on here. Since all processes that have GPU enter the loop, there would be a guaranteed race condition in this loop, as we run over all k-points and do a summation over all q-points. 

Doing similar synchronization pattern as implemented here is safe (and this is actually advised to reduce synchronizations) if we know that there is no overlap between memory regions that are accessed by different processes.

2024-10-14 12:36 UTC, iskakoff commented on src/green/gpu/cugw_qpt.h
> +    bool cleanup_req_;
c++ standard advises to not throwing exceptions in destructor.

2024-10-14 12:36 UTC, iskakoff commented on src/green/gpu/cugw_qpt.h
> +    static int pos = 0;
next three lines does not make sense to me.

2024-10-14 12:41 UTC, egull commented on src/green/gpu/cugw_qpt.h
> +    bool cleanup_req_;
That's right. I guess we need to print an error and abort the program. This should never happen unless there's a logic error anyway.

2024-10-14 12:44 UTC, egull commented on src/cu_routines.cu
> +      MPI_Win_lock_all(MPI_MODE_NOCHECK, sigma_tau_host_shared.win());
You're a bit late to that party. We'll discuss today how to do that in a way that is both performant (which your solution is not) and correct (which his solution is not). The way I think it works is via 

MPI_Win_lock_all
MPI_Win_sync
...then do the update/access
MPI_Win_sync
MPI_Win_flush_all
MPI_Win_unlock_all

the MPI_Win_sync at most syncronizes a private with a public version, but may not syncronize the private version of other threads. The standard section 11 has more.

2024-10-14 13:28 UTC, iskakoff commented on src/cu_routines.cu
> +      MPI_Win_lock_all(MPI_MODE_NOCHECK, sigma_tau_host_shared.win());
Which my implementation is not performant? 

Also, `mpi_win_flush` is not needed here, we don't do any RMA operations on shared window here.

2025-11-06 17:10 UTC, gauravharsha commented
Closing. Superseded by #9

2025-11-06 17:10 UTC, closed without merging